branches:
  only:
  - main
language: python
python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip setuptools pytest
install:
  - python setup.py install
script:
  - pytest --disable-warnings