branches:
  only:
  - main

language: python
after_success:
  - bash <(curl -s https://codecov.io/bash)

python:
  - "3.8"
before_install:
  - python -m pip install --upgrade pip setuptools pytest coverage
install:
  - python setup.py install

script:
  - coverage run --source aestoolbox -m pytest
  - coverage report -m